# Generated by Django 5.1 on 2024-08-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_tg_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="tg_id",
            field=models.BigIntegerField(unique=True, verbose_name="телеграм ID"),
        ),
    ]
