# Generated by Django 5.1 on 2024-08-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveIntegerField(default=1, help_text='в днях', verbose_name='периодичность'),
        ),
    ]
