# Generated by Django 5.1 on 2024-08-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"verbose_name": "привычка", "verbose_name_plural": "привычки"},
        ),
    ]
