# Generated by Django 5.1 on 2024-08-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_habit_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.DurationField(blank=True, help_text='секунд', null=True, verbose_name='время на выполнение'),
        ),
    ]
