name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django psycopg2-binary coverage

      - name: Create coverage configuration
        run: |
          echo "[run]" > .coveragerc
          echo "omit = */migrations/*,*/tests/*,*/config/*,*/__init__.py*,*manage.py*" >> .coveragerc
          echo "[report]" >> .coveragerc
          echo "exclude_lines =" >> .coveragerc
          echo "    pragma: no cover" >> .coveragerc
          echo "    def __str__" >> .coveragerc
          echo "    if self\.debug" >> .coveragerc
          echo "    def __repr__" >> .coveragerc

      - name: Run tests with coverage
        run: |
          python manage.py migrate
          coverage run --rcfile=.coveragerc --source='.' manage.py test
          coverage report -m --fail-under=80
